'use client'

import { useState, useEffect, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import { Shield } from 'lucide-react'
import Link from 'next/link'
import { motion, AnimatePresence } from 'framer-motion'
import CustomVehicleReport from '@/components/CustomVehicleReport'
import type { ParsedPPSRData } from '@/lib/ppsr-data-parser'

const TESTIMONIALS = [
  {
    text: "Car Verify saved me from buying a stolen vehicle. The report was instant and comprehensive!",
    author: "Sarah M.",
    location: "Sydney, NSW"
  },
  {
    text: "Found out the car had $15,000 in finance owing. Dodged a bullet thanks to this service!",
    author: "James T.",
    location: "Melbourne, VIC"
  },
  {
    text: "Super fast and easy to use. Got my PPSR certificate in under a minute!",
    author: "Lisa K.",
    location: "Brisbane, QLD"
  },
  {
    text: "The detailed report helped me negotiate a better price. Worth every cent!",
    author: "Michael R.",
    location: "Perth, WA"
  },
  {
    text: "Peace of mind before the big purchase. Highly recommend to anyone buying a used car!",
    author: "Emma W.",
    location: "Adelaide, SA"
  }
]

function PaymentSuccessContent() {
  const searchParams = useSearchParams()
  const sessionId = searchParams.get('session_id')

  const [status, setStatus] = useState<'verifying' | 'generating' | 'complete' | 'error'>('verifying')
  const [progress, setProgress] = useState(0)
  const [error, setError] = useState<string | null>(null)
  const [reportData, setReportData] = useState<any>(null)
  const [vehicleData, setVehicleData] = useState<any>(null)
  const [parsedData, setParsedData] = useState<ParsedPPSRData | null>(null)
  const [currentTestimonialIndex, setCurrentTestimonialIndex] = useState(0)

  // Cycle through testimonials every 3 seconds
  useEffect(() => {
    if (status === 'verifying' || status === 'generating') {
      const interval = setInterval(() => {
        setCurrentTestimonialIndex((prev) => (prev + 1) % TESTIMONIALS.length)
      }, 3000)
      return () => clearInterval(interval)
    }
  }, [status])

  useEffect(() => {
    if (!sessionId) {
      setError('No session ID found')
      setStatus('error')
      return
    }

    verifyPaymentAndGenerateReport()
  }, [sessionId])

  const verifyPaymentAndGenerateReport = async () => {
    try {
      setStatus('verifying')
      setProgress(25)

      // Fetch the report from the database (generated by webhook)
      const reportResponse = await fetch('/api/get-report-by-session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sessionId }),
      })

      if (!reportResponse.ok) {
        // Report might not be ready yet, poll for up to 30 seconds
        console.log('Report not ready yet, polling...')
        let attempts = 0
        const maxAttempts = 15 // 15 attempts × 2 seconds = 30 seconds
        let reportData = null

        setCurrentStage('Building your report...')

        while (attempts < maxAttempts) {
          await new Promise(resolve => setTimeout(resolve, 2000)) // Wait 2 seconds
          attempts++
          setProgress(25 + (attempts * 5)) // Increase progress slowly

          console.log(`Polling attempt ${attempts}/${maxAttempts}`)

          const retryResponse = await fetch('/api/get-report-by-session', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ sessionId }),
          })

          if (retryResponse.ok) {
            reportData = await retryResponse.json()
            console.log('Report found!')
            break
          } else {
            const errorText = await retryResponse.text()
            console.log(`Attempt ${attempts} failed:`, errorText)
          }
        }

        if (!reportData) {
          console.error('Report not found after polling')
          throw new Error('Your report is still being generated. We\'ve sent it to your email - please check your inbox!')
        }

        setReportData(reportData)
        if (reportData.report?.metadata) {
          setVehicleData(reportData.report.metadata)
        }
        if (reportData.report?.parsedData) {
          setParsedData(reportData.report.parsedData)
        }
      } else {
        const reportData = await reportResponse.json()
        console.log('Report found immediately!')
        setReportData(reportData)
        if (reportData.report?.metadata) {
          setVehicleData(reportData.report.metadata)
        }
        if (reportData.report?.parsedData) {
          setParsedData(reportData.report.parsedData)
        }
      }

      setProgress(100)
      setStatus('complete')

      console.log('✅ Report loaded successfully')
      console.log('Report data:', reportData)
      console.log('Has PDF data?', !!reportData?.report?.pdfBase64)
      console.log('Has parsed data?', !!reportData?.report?.parsedData)

    } catch (err) {
      console.error('Error:', err)
      setError(err instanceof Error ? err.message : 'Something went wrong')
      setStatus('error')
    }
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-gray-100">
        <div className="container mx-auto px-4 py-3 sm:py-4">
          <Link href="/" className="flex items-center justify-center space-x-2 sm:space-x-3">
            <div className="bg-blue-600 p-1.5 sm:p-2 rounded-lg">
              <Shield className="h-5 w-5 sm:h-6 sm:w-6 text-white" />
            </div>
            <div>
              <span className="text-xl sm:text-2xl font-bold text-gray-900">Car Verify</span>
              <div className="text-[10px] sm:text-xs text-blue-600 font-medium">AUTHORISED PPSR PROVIDER</div>
            </div>
          </Link>
        </div>
      </header>

      <div className="container mx-auto px-4 py-6 sm:py-12">
        {/* Loading/Generating State */}
        {(status === 'verifying' || status === 'generating') && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-2xl mx-auto text-center"
          >
            <div className="mb-6 sm:mb-8">
              <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-gray-900 mb-3 sm:mb-4 px-2">
                {status === 'verifying' ? 'Verifying Payment...' : 'Building Your Report...'}
              </h1>
              <p className="text-base sm:text-lg text-gray-600 px-2">
                {status === 'verifying'
                  ? 'Please wait while we confirm your payment'
                  : 'Generating your comprehensive PPSR report'}
              </p>
            </div>

            {/* Progress Bar */}
            <div className="mb-6 sm:mb-8 px-2">
              <div className="w-full bg-gray-200 rounded-full h-3 sm:h-4 overflow-hidden">
                <motion.div
                  className="h-full bg-gradient-to-r from-blue-500 to-blue-600"
                  initial={{ width: '0%' }}
                  animate={{ width: `${progress}%` }}
                  transition={{ duration: 0.5 }}
                />
              </div>
              <p className="text-sm sm:text-base text-gray-600 mt-2">{progress}% Complete</p>
            </div>

            {/* Loading Animation */}
            <div className="flex justify-center mb-6 sm:mb-8">
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                className="w-12 h-12 sm:w-16 sm:h-16 border-3 sm:border-4 border-blue-600 border-t-transparent rounded-full"
              />
            </div>

            {vehicleData && (
              <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 sm:p-6 mb-6 sm:mb-8 mx-2">
                <p className="text-sm sm:text-base text-blue-900 font-semibold">
                  Generating report for: {vehicleData.year} {vehicleData.make} {vehicleData.model}
                </p>
                <p className="text-xs sm:text-sm text-blue-700 mt-1">
                  {vehicleData.rego} ({vehicleData.state})
                </p>
              </div>
            )}

            {/* Cycling Testimonials */}
            <div className="mt-8 sm:mt-12 px-2">
              <div className="relative min-h-[160px] sm:min-h-[140px]">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={currentTestimonialIndex}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    transition={{ duration: 0.5 }}
                    className="bg-white border border-gray-200 rounded-xl p-6 sm:p-8 shadow-sm"
                  >
                    <div className="flex items-start mb-4">
                      <div className="text-blue-600 text-3xl sm:text-4xl mr-2 leading-none">"</div>
                      <p className="text-sm sm:text-base text-gray-700 italic pt-1 sm:pt-2">
                        {TESTIMONIALS[currentTestimonialIndex].text}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs sm:text-sm font-semibold text-gray-900">
                        {TESTIMONIALS[currentTestimonialIndex].author}
                      </p>
                      <p className="text-xs text-gray-500">
                        {TESTIMONIALS[currentTestimonialIndex].location}
                      </p>
                    </div>
                  </motion.div>
                </AnimatePresence>
              </div>

              {/* Testimonial Indicators */}
              <div className="flex justify-center gap-2 mt-4">
                {TESTIMONIALS.map((_, index) => (
                  <div
                    key={index}
                    className={`h-1.5 rounded-full transition-all duration-300 ${
                      index === currentTestimonialIndex
                        ? 'w-8 bg-blue-600'
                        : 'w-1.5 bg-gray-300'
                    }`}
                  />
                ))}
              </div>
            </div>
          </motion.div>
        )}

        {/* Error State */}
        {status === 'error' && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-2xl mx-auto text-center"
          >
            <div className="bg-red-50 border border-red-200 rounded-xl p-6 sm:p-8 mx-2">
              <h1 className="text-2xl sm:text-3xl font-bold text-red-900 mb-3 sm:mb-4">
                Oops! Something went wrong
              </h1>
              <p className="text-sm sm:text-base text-red-700 mb-4 sm:mb-6">{error}</p>
              <Link
                href="/"
                className="inline-block px-5 sm:px-6 py-2.5 sm:py-3 bg-blue-600 text-white text-sm sm:text-base font-semibold rounded-lg hover:bg-blue-700 transition-colors"
              >
                Return to Homepage
              </Link>
            </div>
          </motion.div>
        )}

        {/* Complete State - Show Custom Report */}
        {status === 'complete' && reportData && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="w-full"
          >
            {/* Success Header */}
            <div className="text-center mb-8 px-4">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
                className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-green-400 to-green-600 rounded-full mb-4 shadow-lg"
              >
                <svg className="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                </svg>
              </motion.div>
              <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-gray-900 mb-3">
                Your PPSR Report is Ready!
              </h1>
              {vehicleData && (
                <p className="text-lg sm:text-xl text-gray-600 font-medium">
                  {vehicleData.year} {vehicleData.make} {vehicleData.model}
                </p>
              )}
            </div>

            {/* Show Custom Report if we have parsed data */}
            {parsedData ? (
              <div className="mb-8">
                <CustomVehicleReport {...parsedData} />

                {/* Download Official PPSR Certificate Section */}
                <div className="max-w-5xl mx-auto mt-8 px-4">
                  <div className="bg-blue-50 border-2 border-blue-200 rounded-xl p-6">
                    <div className="flex items-start justify-between">
                      <div>
                        <h3 className="text-lg font-bold text-gray-900 mb-2 flex items-center">
                          <svg className="w-6 h-6 mr-2 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                          </svg>
                          Official PPSR Certificate
                        </h3>
                        <p className="text-sm text-gray-700">Download the official government-issued PPSR certificate for your records</p>
                      </div>
                      <a
                        href={reportData.report?.pdfBase64 ? `data:application/pdf;base64,${reportData.report.pdfBase64}` : '#'}
                        download={reportData.report?.filename || 'PPSR_Certificate.pdf'}
                        className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white font-bold rounded-lg hover:bg-blue-700 transition-all shadow-lg hover:shadow-xl"
                      >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                        Download PDF
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              /* Fallback: Show raw PPSR certificate if no parsed data */
              <div className="max-w-5xl mx-auto">
                {/* PPSR Report Card */}
                <div className="bg-white rounded-2xl shadow-2xl border border-gray-200 overflow-hidden mx-4">
              {/* Card Header */}
              <div className="bg-gradient-to-r from-blue-600 to-indigo-600 px-6 py-6">
                <h2 className="text-2xl sm:text-3xl font-bold text-white flex items-center">
                  <svg className="w-8 h-8 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                  </svg>
                  Official PPSR Certificate
                </h2>
                <p className="text-blue-100 mt-2">Official government-issued vehicle security check</p>
              </div>

              {/* Report Details */}
              <div className="p-6 bg-gradient-to-br from-gray-50 to-blue-50">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                  <div className="bg-white rounded-lg p-4 border border-gray-200 shadow-sm">
                    <div className="text-sm text-gray-600 mb-1">Certificate ID</div>
                    <div className="text-lg font-bold text-gray-900">{reportData.report?.filename || 'PPSR Certificate'}</div>
                  </div>
                  <div className="bg-white rounded-lg p-4 border border-gray-200 shadow-sm">
                    <div className="text-sm text-gray-600 mb-1">Generated</div>
                    <div className="text-lg font-bold text-gray-900">
                      {reportData.report?.generatedAt ? new Date(reportData.report.generatedAt).toLocaleString() : 'Just now'}
                    </div>
                  </div>
                </div>

                {/* What's Included */}
                <div className="bg-white rounded-lg p-5 border border-gray-200 shadow-sm mb-6">
                  <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <svg className="w-6 h-6 mr-2 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    What's Included
                  </h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div className="flex items-start">
                      <svg className="w-5 h-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      <span className="text-sm text-gray-700">Finance Owing / Security Interests</span>
                    </div>
                    <div className="flex items-start">
                      <svg className="w-5 h-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      <span className="text-sm text-gray-700">Stolen Vehicle Status</span>
                    </div>
                    <div className="flex items-start">
                      <svg className="w-5 h-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      <span className="text-sm text-gray-700">Write-Off History (WOVR)</span>
                    </div>
                    <div className="flex items-start">
                      <svg className="w-5 h-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      <span className="text-sm text-gray-700">Official AFSA Certificate</span>
                    </div>
                  </div>
                </div>

                {/* PDF Preview */}
                {reportData.report?.pdfBase64 && (
                  <div className="bg-white rounded-lg border-2 border-gray-300 overflow-hidden shadow-md mb-6">
                    <div className="bg-gray-100 px-4 py-2 border-b border-gray-300">
                      <p className="text-sm font-semibold text-gray-700">Certificate Preview</p>
                    </div>
                    <iframe
                      src={`data:application/pdf;base64,${reportData.report.pdfBase64}`}
                      className="w-full"
                      style={{ height: '600px' }}
                      title="PPSR Certificate"
                    />
                  </div>
                )}

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row gap-3">
                  {reportData.report?.pdfBase64 ? (
                    <a
                      href={`data:application/pdf;base64,${reportData.report.pdfBase64}`}
                      download={reportData.report?.filename || 'PPSR_Certificate.pdf'}
                      className="flex-1 flex items-center justify-center gap-2 py-4 bg-gradient-to-r from-blue-600 to-blue-700 text-white text-base font-bold rounded-xl hover:from-blue-700 hover:to-blue-800 transition-all transform hover:scale-105 shadow-lg hover:shadow-xl"
                    >
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      Download PDF
                    </a>
                  ) : (
                    <button
                      disabled
                      className="flex-1 flex items-center justify-center gap-2 py-4 bg-gray-300 text-gray-500 text-base font-bold rounded-xl cursor-not-allowed"
                    >
                      <svg className="w-5 h-5 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                      </svg>
                      Generating PDF...
                    </button>
                  )}
                  <Link
                    href="/account"
                    className="flex-1 flex items-center justify-center gap-2 py-4 bg-gradient-to-r from-gray-100 to-gray-200 text-gray-900 text-base font-bold rounded-xl hover:from-gray-200 hover:to-gray-300 transition-all border-2 border-gray-300 hover:border-gray-400"
                  >
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                    View My Account
                  </Link>
                </div>

                {/* Email Confirmation */}
                <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <div className="flex items-start">
                    <svg className="w-6 h-6 text-blue-600 mr-3 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                    <div>
                      <p className="text-sm font-semibold text-blue-900">Certificate Sent to Your Email</p>
                      <p className="text-sm text-blue-700 mt-1">A copy has been sent to your email address with full details and your account login information.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

                {/* Next Steps */}
                <div className="mt-8 px-4">
                  <div className="bg-gradient-to-r from-green-50 to-blue-50 rounded-xl p-6 border border-green-200">
                    <h3 className="text-lg font-bold text-gray-900 mb-3">What's Next?</h3>
                    <div className="space-y-2 text-sm text-gray-700">
                      <p>✅ Your PPSR certificate is ready to download</p>
                      <p>✅ A copy has been emailed to you</p>
                      <p>✅ You can access it anytime from your account</p>
                      <p>✅ You have unlimited checks with your subscription</p>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </motion.div>
        )}
      </div>
    </div>
  )
}

export default function PaymentSuccessPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="text-center">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
            className="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full mx-auto mb-4"
          />
          <p className="text-gray-600">Loading...</p>
        </div>
      </div>
    }>
      <PaymentSuccessContent />
    </Suspense>
  )
}
